#! /bin/sh

xrandr --output DP-0 --primary --mode 1920x1080 --rate 75
xrandr --output HDMI-0 --mode 1920x1080 --rate 60 --right-of DP-O

sxhkd & 
wal -i ~/wallpapers/wallpaper_mountain.jpg


bspc monitor DP-0 -d 1 2 3 4 5 
bspc monitor HDMI-0 -d 1 2 3 4 5 

bspc config window_gap 20
bspc config border_width 1
bspc config top_padding 45

bspc rule -a Screenkey manage=off

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"

$HOME/.config/polybar/launch.sh &
feh --bg-scale ~/wallpapers/wallpaper_mountain.jpg
picom &
